name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  radon-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies and run full test suite
        run: |
          python -m pip install -r requirements-dev.txt
          make test
